---
name: Lint

on:
  workflow_call:

jobs:
  lint-ruby:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Run RuboCop linter
        run: bundle exec rubocop
